### ISSUE TITLE
Bug: Unexpected instruction encoding on 32bit build

### ISSUE THREAD

**Issue by zuypt** [googleprojectzero/Jackalope#11]
I hit this assertion on the 32bit build of Jackalope but it works fine under 64bit build.
`
[-] PROGRAM ABORT : Unexpected instruction encoding         Location : LiteCov::InstrumentInstruction(), D:\Jackalope\TinyInst\litecov.cpp:733
`
Also there is typo in the nearby comment `// check hat the offset is at the end`.

**Comment by ifratric** [comment]
Ooops :-) Should be fixed now! Please update TinyInst and rebuild.

**Comment by ifratric** [comment]
Tentatively closing the issue.
