### ISSUE TITLE
templates like in Domato

### ISSUE THREAD

**Issue by adrian-rt** [googleprojectzero/Jackalope#20]
Hi,

I see that the grammar files are same as in Domato, but is there no support for templates too, like
https://github.com/googleprojectzero/domato/blob/master/jscript/template.html ?

Say for example, I'd like to fuzz some PDF readers, templates for PDFs would be great and then I could generate the javascript using this.....

thanks.

**Comment by ifratric** [comment]
I agree it would be useful. For now though, there are a couple of ways to get around this limitation
 - Define a "template" as part of the grammar, e.g.
   `<root> = %PDF-1.7<lf>...<javascript>...`

 - Modify `GrammarFuzzer::OutputFilter` to insert the template around the output sample
