### ISSUE TITLE
ibc++abi.dylib: terminating with uncaught exception of type int

### ISSUE THREAD

**Issue by dgh05t** [googleprojectzero/Jackalope#4]
Hi,
when I fuzzing MacOS program, It constant show some log like below:
```
...
ibc++abi.dylib: terminating with uncaught exception of type int
Exception at address 0x7fff69bba33a
...
```
which makes fuzzing speed very low.
and it keeps crash( only 1 unique ), and crash file name is like **flaky_...** which means **TryReproduceCrash** failed. I try to reproduce it manually and it doesn't crash either.
Where's my problem? Thank you!

**Comment by ifratric** [comment]
In general, this type of error can be resolved by passing `-patch_return_addresses` flag. For more details, see https://github.com/googleprojectzero/TinyInst#return-address-patching

**Comment by ifratric** [comment]
Now also with `-generate_unwind`, which is more performant than `-patch_return_addresses`.
