### ISSUE TITLE
How  can I add new samples to an existing session?

### ISSUE THREAD

**Issue by dms1lva** [googleprojectzero/Jackalope#43]
In the case where I myself found new samples to add to the corpus, can I add them to an existing session? If so, how? I am not sure if simply adding them to the "samples" directory will be "noticed" by the fuzzer. Also, using "-resume" with a new input folder does not seem to work.

**Comment by ifratric** [comment]
Adding new samples in an existing session is not doable at the moment (though it is an interesting use case that I'd like to support in the future). You can however start a new session with an input that combines samples found by the old session and the new samples you want to add.

**Comment by dms1lva** [comment]
Cool, thanks for the answer!
