### ISSUE TITLE
Build fails on macOS

### ISSUE THREAD

**Issue by r3ggi** [googleprojectzero/Jackalope#5]
During build on macOS cmake raises the following error:

`/path/Jackalope/fuzzer.cpp:30:10: fatal error: 'mersenne.h' file not found`

I changed:

https://github.com/googleprojectzero/Jackalope/blob/b22c8dc641204eee0312fa9a9b785ed64c13a0f2/fuzzer.cpp#L30

to:

`#include "third_party/Mersenne/mersenne.h"` and now it works. :-)

**Comment by ifratric** [comment]
Hmm, not sure why this would fail considering the following line: https://github.com/googleprojectzero/Jackalope/blob/main/CMakeLists.txt#L22

**Comment by r3ggi** [comment]
Hmm, maybe because the

https://github.com/googleprojectzero/Jackalope/blob/b22c8dc641204eee0312fa9a9b785ed64c13a0f2/CMakeLists.txt#L22

includes `mersenne` directory, but the directory is `Mersenne`.

**Comment by ifratric** [comment]
Ah, good point! Should be fixed now!
