### ISSUE TITLE
Implementing network fuzzing

### ISSUE THREAD

**Issue by dms1lva** [googleprojectzero/Jackalope#51]
Hello Ivan,

I'm looking at implementing network fuzzing in jackalope. I understand I can modify the CreateSampleDelivery method and implement my own SampleDelivery to send tcp data. What I don't understand, is that when DeliverSample is called the first time, the server is not running. Also, coverage data seems to be gathered after DeliverSample is called. 

I need a bit of guidance on how to implement this correctly

**Comment by ifratric** [comment]
Hi Dario,

You are correct, with the current Jackalope architecture, there is no guarantee that the target process exists when SampleDelivery is called. Another problem is that in Jackalope, the fuzzing thread is blocked while the target runs (as (a) Jackalope serves as a debugger for the target process and waits for events while the target runs and (b) everything happens on a single thread).

So then, the "correct" (IMHO) way to implement network fuzzing is to add a custom SampleDelivery that spawns a new thread and sends the sample from that thread. It could then wait for the target process to spawn (or simply repeatedly retry sending the sample until it succeeds).

In Jackalope, coverage is collected when the target function returns (or when the target process exits in case the target function is not defined).

**Comment by dms1lva** [comment]
Thank you! That strategy worked out!
