### ISSUE TITLE
Program abort due to `Process hanged before reaching the target method`

### ISSUE THREAD

**Issue by Lyutoon** [googleprojectzero/Jackalope#52]
Hi, 
Thanks for you to develop this awesome tool! Recently I'm trying to fuzz ImageIO and I always got process aborted due to `Process hanged before reaching the target method` when the thread becomes more than 1. So I'm wondering if you have some experiences about how to deal with this?

Thanks!

**Comment by jyadll** [comment]
Hi,
What is your solution?
