### ISSUE TITLE
compile error win x64

### ISSUE THREAD

**Issue by jplopezy** [googleprojectzero/Jackalope#7]
Hello people!

I have a problem when i try to compile it on winx64 ,visual studio x64 and python-3.9.1.

Steps

git clone --recurse-submodules https://github.com/googleprojectzero/TinyInst.git -> ok

cmake -G "Visual Studio 16 2019" -A x64 -> ok

cmake --build . --config Release -> ERROR

output

Microsoft (R) Build Engine versión 16.8.2+25e4d540b para .NET Framework
Copyright (C) Microsoft Corporation. Todos los derechos reservados.

  Checking Build System
  Building Xed
  [UCRT Version] 10.0.10240.0
  [FOUND MS VERSION] 14
  [PYTHON VERSION] 3.9.1
  [GIT VERSION] 12.0.1
  [EXTF PROCESSING] C:/TinyInst/third_party/xed/datafiles/files.cfg
  [EXTF PROCESSING] C:/TinyInst/third_party/xed/datafiles/files-xregs.cfg
  [EXTF PROCESSING] C:/TinyInst/third_party/xed/datafiles/via/files-via-padlock.cfg
  [EXTF PROCESSING] C:/TinyInst/third_party/xed/datafiles/amd/files-amd.cfg
  [EXTF PROCESSING] C:/TinyInst/third_party/xed/datafiles/amd/amdxop/files.cfg
  [EXTF PROCESSING] C:/TinyInst/third_party/xed/datafiles/mpx/files.cfg
  [EXTF PROCESSING] C:/TinyInst/third_party/xed/datafiles/cet/files.cfg
  [EXTF PROCESSING] C:/TinyInst/third_party/xed/datafiles/rdrand/files.cfg
  [EXTF PROCESSING] C:/TinyInst/third_party/xed/datafiles/glm/files.cfg
  [EXTF PROCESSING] C:/TinyInst/third_party/xed/datafiles/sha/files.cfg
  [EXTF PROCESSING] C:/TinyInst/third_party/xed/datafiles/xsaveopt/files.cfg
  [EXTF PROCESSING] C:/TinyInst/third_party/xed/datafiles/xsaves/files.cfg
  [EXTF PROCESSING] C:/TinyInst/third_party/xed/datafiles/xsavec/files.cfg
  [EXTF PROCESSING] C:/TinyInst/third_party/xed/datafiles/clflushopt/files.cfg
  [EXTF PROCESSING] C:/TinyInst/third_party/xed/datafiles/rdseed/files.cfg
  [EXTF PROCESSING] C:/TinyInst/third_party/xed/datafiles/fsgsbase/files.cfg
  [EXTF PROCESSING] C:/TinyInst/third_party/xed/datafiles/smap/files.cfg
  [EXTF PROCESSING] C:/TinyInst/third_party/xed/datafiles/sgx/files.cfg
  [EXTF PROCESSING] C:/TinyInst/third_party/xed/datafiles/rdpid/files.cfg
  [EXTF PROCESSING] C:/TinyInst/third_party/xed/datafiles/pt/files.cfg
  [EXTF PROCESSING] C:/TinyInst/third_party/xed/datafiles/tremont/files.cfg
  [EXTF PROCESSING] C:/TinyInst/third_party/xed/datafiles/movdir/files.cfg
  [EXTF PROCESSING] C:/TinyInst/third_party/xed/datafiles/waitpkg/files.cfg
  [EXTF PROCESSING] C:/TinyInst/third_party/xed/datafiles/cldemote/files.cfg
  [EXTF PROCESSING] C:/TinyInst/third_party/xed/datafiles/sgx-enclv/files.cfg
  [EXTF PROCESSING] C:/TinyInst/third_party/xed/datafiles/avx/files.cfg
  [Clearing file list for type dec-spine: [ C:/TinyInst/third_party/xed/datafiles/xed-spine.txt ]]
  [EXTF PROCESSING] C:/TinyInst/third_party/xed/datafiles/ivbavx/files.cfg
  [EXTF PROCESSING] C:/TinyInst/third_party/xed/datafiles/hswavx/files.cfg
  [EXTF PROCESSING] C:/TinyInst/third_party/xed/datafiles/hswbmi/files.cfg
  [EXTF PROCESSING] C:/TinyInst/third_party/xed/datafiles/hsw/files.cfg
  [EXTF PROCESSING] C:/TinyInst/third_party/xed/datafiles/bdw/files.cfg
  [EXTF PROCESSING] C:/TinyInst/third_party/xed/datafiles/skl/files.cfg
  [EXTF PROCESSING] C:/TinyInst/third_party/xed/datafiles/skx/files.cfg
  [EXTF PROCESSING] C:/TinyInst/third_party/xed/datafiles/pku/files.cfg
  [EXTF PROCESSING] C:/TinyInst/third_party/xed/datafiles/clwb/files.cfg
  [EXTF PROCESSING] C:/TinyInst/third_party/xed/datafiles/clx/files.cfg
  [EXTF PROCESSING] C:/TinyInst/third_party/xed/datafiles/vnni/files.cfg
  [EXTF PROCESSING] C:/TinyInst/third_party/xed/datafiles/cpx/files.cfg
  [EXTF PROCESSING] C:/TinyInst/third_party/xed/datafiles/avx512-bf16/files.cfg
  [EXTF PROCESSING] C:/TinyInst/third_party/xed/datafiles/knl/files.cfg
  [EXTF PROCESSING] C:/TinyInst/third_party/xed/datafiles/knm/files.cfg
  [EXTF PROCESSING] C:/TinyInst/third_party/xed/datafiles/4fmaps-512/files.cfg
  [EXTF PROCESSING] C:/TinyInst/third_party/xed/datafiles/4vnniw-512/files.cfg
  [EXTF PROCESSING] C:/TinyInst/third_party/xed/datafiles/vpopcntdq-512/files.cfg
  [EXTF PROCESSING] C:/TinyInst/third_party/xed/datafiles/avx512f/shared-files.cfg
  [Clearing file list for type dec-spine: [ C:/TinyInst/third_party/xed/datafiles/avx/avx-spine.txt ]]
  CONSIDERING SOURCE C:\TinyInst\third_party\xed\datafiles\knc\xed-operand-values-interface-uisa.c source 1
  ADDING SOURCE C:\TinyInst\third_party\xed\datafiles\knc\xed-operand-values-interface-uisa.c source 1
  [EXTF PROCESSING] C:/TinyInst/third_party/xed/datafiles/avx512f/files.cfg
  [EXTF PROCESSING] C:/TinyInst/third_party/xed/datafiles/avx512cd/files.cfg
  [EXTF PROCESSING] C:/TinyInst/third_party/xed/datafiles/avx512-skx/files.cfg
  [EXTF PROCESSING] C:/TinyInst/third_party/xed/datafiles/cnl/files.cfg
  [EXTF PROCESSING] C:/TinyInst/third_party/xed/datafiles/avx512ifma/files.cfg
  [EXTF PROCESSING] C:/TinyInst/third_party/xed/datafiles/avx512vbmi/files.cfg
  [EXTF PROCESSING] C:/TinyInst/third_party/xed/datafiles/icl/files.cfg
  [EXTF PROCESSING] C:/TinyInst/third_party/xed/datafiles/wbnoinvd/files.cfg
  [EXTF PROCESSING] C:/TinyInst/third_party/xed/datafiles/pconfig/files.cfg
  [EXTF PROCESSING] C:/TinyInst/third_party/xed/datafiles/bitalg/files.cfg
  [EXTF PROCESSING] C:/TinyInst/third_party/xed/datafiles/vbmi2/files.cfg
  [EXTF PROCESSING] C:/TinyInst/third_party/xed/datafiles/gfni-vaes-vpcl/files-sse.cfg
  [EXTF PROCESSING] C:/TinyInst/third_party/xed/datafiles/gfni-vaes-vpcl/files-avx-avx512.cfg
  [EXTF PROCESSING] C:/TinyInst/third_party/xed/datafiles/vpopcntdq-vl/files.cfg
  [EXTF PROCESSING] C:/TinyInst/third_party/xed/datafiles/tgl/files.cfg
  [EXTF PROCESSING] C:/TinyInst/third_party/xed/datafiles/vp2intersect/files.cfg
  [EXTF PROCESSING] C:/TinyInst/third_party/xed/datafiles/keylocker/files.cfg
  [EXTF PROCESSING] C:/TinyInst/third_party/xed/datafiles/adl/files.cfg
  [EXTF PROCESSING] C:/TinyInst/third_party/xed/datafiles/hreset/files.cfg
  [EXTF PROCESSING] C:/TinyInst/third_party/xed/datafiles/avx-vnni/files.cfg
  [EXTF PROCESSING] C:/TinyInst/third_party/xed/datafiles/spr/files.cfg
  [EXTF PROCESSING] C:/TinyInst/third_party/xed/datafiles/uintr/files.cfg
  [EXTF PROCESSING] C:/TinyInst/third_party/xed/datafiles/amx-spr/files.cfg
  [EXTF PROCESSING] C:/TinyInst/third_party/xed/datafiles/enqcmd/files.cfg
  [EXTF PROCESSING] C:/TinyInst/third_party/xed/datafiles/tsx-ldtrk/files.cfg
  [EXTF PROCESSING] C:/TinyInst/third_party/xed/datafiles/serialize/files.cfg
  [EXTF PROCESSING] C:/TinyInst/third_party/xed/datafiles/future/files.cfg
  [EXTF PROCESSING] C:/TinyInst/third_party/xed/datafiles/tdx/files.cfg
  ABORT: Library build failed
  [EMIT BUILD DEFINES HEADER FILE]
  R: 1 P: 0 C: 0 E: 0 / 36 msecs [decprep]
  [TOUCH] obj/dummy-prep
  R: 0 P: 0 C: 1 E: 0 / 721 msecs
        BUILT: C:\TinyInst\third_party\obj\dummy-prep
  R: 2 P: 0 C: 1 E: 0 / 721 msecs [decgen encgen]
  [WRITING] obj/ENC-OUT.txt
  [WRITING] obj/ENC-ERR.txt
  [ENC-GEN] Return code: 0
  R: 1 P: 0 C: 2 E: 0 / 12 secs [decgen]
        BUILT: C:\TinyInst\third_party\obj\ENCGEN-OUTPUT-FILES.txt
  [WRITING] obj/DEC-OUT.txt
  [WRITING] obj/DEC-ERR.txt
  [DEC-GEN] Return code: 0
  R: 0 P: 0 C: 3 E: 0 / 15 secs
        BUILT: C:\TinyInst\third_party\obj\DECGEN-OUTPUT-FILES.txt
  R: 4 P: 109 C: 0 E: 0 / 25 msecs
  [MBUILD WARNING] Command execution failed. Waiting for remaining jobs and exiting.
  R: 3 P: 109 C: 1 E: 1 / 34 msecs
  [COMMAND     ] "C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64/cl.exe" -IC:/TinyInst/third_party/xe
  d/include/private -IC:/TinyInst/third_party/xed/include/public/xed -IC:/TinyInst/third_party/xed/include/public -Iobj
   -Iobj/include-private     /nologo  /MT  /favor:EM64T  /W4 /WX /wd4091 /wd4127 /wd4505 /wd4702 /wd4244 /wd4292 /DXED_
  GIT_VERSION="12.0.1" /DXED_AMD_ENABLED /DXED_VIA_ENABLED /DXED_AVX /DXED_SUPPORTS_AVX512 /DXED_MPX /DXED_CET /DXED_SU
  PPORTS_SHA /DXED_SUPPORTS_WBNOINVD /DXED_DECODER /DXED_ENCODER /DXED_SUPPORTS_LZCNT_TZCNT /DXED_BUILD /c /Foobj/xed-r
  eg-enum.obj C:/TinyInst/third_party/obj/xed-reg-enum.c
  [EXIT_STATUS ] 399
  [STDERR]

  COMMAND ENCOUNTERD AN EXCEPTION
  Traceback (most recent call last):
    File "C:/TinyInst/third_party/xed\..\mbuild\mbuild\util.py", line 1043, in run
      self.sub = subprocess.Popen(cmd_args,
    File "C:\Users\test\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 947, in __init__
      self._execute_child(args, executable, preexec_fn, close_fds,
    File "C:\Users\test\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 1416, in _execute_child
      hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
  FileNotFoundError: [WinError 2] El sistema no puede encontrar el archivo especificado

  [MBUILD WARNING] Command execution failed. Waiting for remaining jobs and exiting.
  R: 2 P: 109 C: 2 E: 2 / 34 msecs
  [COMMAND     ] "C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64/cl.exe" -IC:/TinyInst/third_party/xe
  d/include/private -IC:/TinyInst/third_party/xed/include/public/xed -IC:/TinyInst/third_party/xed/include/public -Iobj
   -Iobj/include-private     /nologo  /MT  /favor:EM64T  /W4 /WX /wd4091 /wd4127 /wd4505 /wd4702 /wd4244 /wd4292 /DXED_
  GIT_VERSION="12.0.1" /DXED_AMD_ENABLED /DXED_VIA_ENABLED /DXED_AVX /DXED_SUPPORTS_AVX512 /DXED_MPX /DXED_CET /DXED_SU
  PPORTS_SHA /DXED_SUPPORTS_WBNOINVD /DXED_DECODER /DXED_ENCODER /DXED_SUPPORTS_LZCNT_TZCNT /DXED_BUILD /c /Foobj/xed-o
  perand-ctype-enum.obj C:/TinyInst/third_party/obj/xed-operand-ctype-enum.c
  [EXIT_STATUS ] 399
  [STDERR]

  COMMAND ENCOUNTERD AN EXCEPTION
  Traceback (most recent call last):
    File "C:/TinyInst/third_party/xed\..\mbuild\mbuild\util.py", line 1043, in run
      self.sub = subprocess.Popen(cmd_args,
    File "C:\Users\test\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 947, in __init__
      self._execute_child(args, executable, preexec_fn, close_fds,
    File "C:\Users\test\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 1416, in _execute_child
      hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
  FileNotFoundError: [WinError 2] El sistema no puede encontrar el archivo especificado

  [MBUILD WARNING] Command execution failed. Waiting for remaining jobs and exiting.
  R: 1 P: 109 C: 3 E: 3 / 52 msecs
  [COMMAND     ] "C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64/cl.exe" -IC:/TinyInst/third_party/xe
  d/include/private -IC:/TinyInst/third_party/xed/include/public/xed -IC:/TinyInst/third_party/xed/include/public -Iobj
   -Iobj/include-private     /nologo  /MT  /favor:EM64T  /W4 /WX /wd4091 /wd4127 /wd4505 /wd4702 /wd4244 /wd4292 /DXED_
  GIT_VERSION="12.0.1" /DXED_AMD_ENABLED /DXED_VIA_ENABLED /DXED_AVX /DXED_SUPPORTS_AVX512 /DXED_MPX /DXED_CET /DXED_SU
  PPORTS_SHA /DXED_SUPPORTS_WBNOINVD /DXED_DECODER /DXED_ENCODER /DXED_SUPPORTS_LZCNT_TZCNT /DXED_BUILD /c /Foobj/xed-a
  ddress-width-enum.obj C:/TinyInst/third_party/obj/xed-address-width-enum.c
  [EXIT_STATUS ] 399
  [STDERR]

  COMMAND ENCOUNTERD AN EXCEPTION
  Traceback (most recent call last):
    File "C:/TinyInst/third_party/xed\..\mbuild\mbuild\util.py", line 1043, in run
      self.sub = subprocess.Popen(cmd_args,
    File "C:\Users\test\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 947, in __init__
      self._execute_child(args, executable, preexec_fn, close_fds,
    File "C:\Users\test\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 1416, in _execute_child
      hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
  FileNotFoundError: [WinError 2] El sistema no puede encontrar el archivo especificado

  [MBUILD WARNING] Command execution failed. Waiting for remaining jobs and exiting.
  R: 0 P: 109 C: 4 E: 4 / 52 msecs
  [COMMAND     ] "C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64/cl.exe" -IC:/TinyInst/third_party/xe
  d/include/private -IC:/TinyInst/third_party/xed/include/public/xed -IC:/TinyInst/third_party/xed/include/public -Iobj
   -Iobj/include-private     /nologo  /MT  /favor:EM64T  /W4 /WX /wd4091 /wd4127 /wd4505 /wd4702 /wd4244 /wd4292 /DXED_
  GIT_VERSION="12.0.1" /DXED_AMD_ENABLED /DXED_VIA_ENABLED /DXED_AVX /DXED_SUPPORTS_AVX512 /DXED_MPX /DXED_CET /DXED_SU
  PPORTS_SHA /DXED_SUPPORTS_WBNOINVD /DXED_DECODER /DXED_ENCODER /DXED_SUPPORTS_LZCNT_TZCNT /DXED_BUILD /c /Foobj/xed-a
  ttribute-enum.obj C:/TinyInst/third_party/obj/xed-attribute-enum.c
  [EXIT_STATUS ] 399
  [STDERR]

  COMMAND ENCOUNTERD AN EXCEPTION
  Traceback (most recent call last):
    File "C:/TinyInst/third_party/xed\..\mbuild\mbuild\util.py", line 1043, in run
      self.sub = subprocess.Popen(cmd_args,
    File "C:\Users\test\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 947, in __init__
      self._execute_child(args, executable, preexec_fn, close_fds,
    File "C:\Users\test\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 1416, in _execute_child
      hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
  FileNotFoundError: [WinError 2] El sistema no puede encontrar el archivo especificado

E:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(
238,5): error MSB8066: Compilación personalizada de "C:\TinyInst\CMakeFiles\f09a29e492cfb828c28199765f4d30a1\xed.lib.ru
le;C:\TinyInst\CMakeFiles\da2c2f7724aac5e4ff3af51503004f58\xed.rule" terminada con el código 1. [C:\TinyInst\third_part
y\xed.vcxproj]

**Comment by ifratric** [comment]
Looks like an issue with XED (Intel library for encoding/decoding instructions). Can you build it standalone, by following the instructions in
https://github.com/intelxed/xed#abbreviated-github-building-instructions

**Comment by jplopezy** [comment]
Fixed, I tried it on a clean install and it worked.
