### ISSUE TITLE
output example -  WARNING: Error delivering sample, retrying with a clean target

### ISSUE THREAD

**Issue by jplopezy** [googleprojectzero/Jackalope#8]
Hi people

This question is about this output, i would like to know i'ts correct 

cmd : fuzzer.exe -in in -out out -t 100000 -delivery file -instrument_module test.exe -target_module test.exe -target_method main -nargs 3 -iterations 10 -persist -loop -cmp_coverage -- "test.exe" @@

Total execs: 107988
Unique samples: 1 (0 discarded)
Crashes: 0 (0 unique)
Hangs: 0
Offsets: 27
Execs/s: 31
Instrumented module test.exe, code size: 4096
Result: 2038152770
[!] WARNING: Error delivering sample, retrying with a clean target
Instrumented module test.exe, code size: 4096
Result: 2038152770
[!] WARNING: Error delivering sample, retrying with a clean target
Instrumented module test.exe, code size: 4096
Result: 2038152770
[!] WARNING: Error delivering sample, retrying with a clean target
Instrumented module test.exe, code size: 4096
Result: 2038152770
[!] WARNING: Error delivering sample, retrying with a clean target
Instrumented module test.exe, code size: 4096
Result: 2038152770
[!] WARNING: Error delivering sample, retrying with a clean target
Instrumented module test.exe, code size: 4096
Result: 2038152770
[!] WARNING: Error delivering sample, retrying with a clean target
Instrumented module test.exe, code size: 4096
Result: 2038152770
[!] WARNING: Error delivering sample, retrying with a clean target
Instrumented module test.exe, code size: 4096
Result: 2038152770
[!] WARNING: Error delivering sample, retrying with a clean target
Instrumented module test.exe, code size: 4096
Result: 2038152770
[!] WARNING: Error delivering sample, retrying with a clean target

**Comment by ifratric** [comment]
In your target, you should close the input file handle before returning from the target function. Otherwise, the fuzzer won't be able to open the input file for writing (to replace it's content for the next iteration). The fuzzer "resolves" the case where it can't write next input by killing the target process, but that results in a loss of performance and the warning you encountered.
