### ISSUE TITLE
Crash in AppendMutator::Mutate

### ISSUE THREAD

**Issue by zuypt** [googleprojectzero/Jackalope#9]
I occasionally got crash like this. I think it is from `AppendMutator::Mutate` function (not 100% sure). I have a more than 3MB input file so I suspect it is some kind of integer overflow in that function. I have attached my fuzzer binary below.

```
Faulting application name: fuzzer.exe, version: 0.0.0.0, time stamp: 0x600e3f4d
Faulting module name: fuzzer.exe, version: 0.0.0.0, time stamp: 0x600e3f4d
Exception code: 0xc0000005
Fault offset: 0x00000000000099cb
Faulting process id: 0x36ac
Faulting application start time: 0x01d6f2e23270c8b0
Faulting application path: D:\Jackalope-main\build\Release\fuzzer.exe
Faulting module path: D:\Jackalope-main\build\Release\fuzzer.exe
Report Id: f2d81f83-397f-4f9a-855d-621609c7ba69
Faulting package full name: 
Faulting package-relative application ID: ```


[fuzzer.zip](https://github.com/googleprojectzero/Jackalope/files/5864759/fuzzer.zip)

**Comment by ifratric** [comment]
I see, it's possible that this mutator will misbehave if the input sample is larger than MAX_SAMPLE_SIZE, as declared here:
https://github.com/googleprojectzero/Jackalope/blob/main/sample.h#L21
However I tried to make sure that no sample can be larger than that, as seen in the following lines:
https://github.com/googleprojectzero/Jackalope/blob/main/fuzzer.cpp#L539
https://github.com/googleprojectzero/Jackalope/blob/main/fuzzer.cpp#L597
I must have missed something, will investigate!

In the meantime, you can probably avoid the crash by setting MAX_SAMPLE_SIZE to something larger than your input files.

**Comment by ifratric** [comment]
Can you check if the latest version fixes the issues? (commit https://github.com/googleprojectzero/Jackalope/commit/84b2cd278651b75b7fe95112282c81740de136c4)

**Comment by zuypt** [comment]
I'm no longer having crashes seem fixed. Thanks
